class BibleVerses {
  static const List<Map<String, String>> verses = [
    // Day 1-10
    {'text': 'The Lord is my shepherd; I shall not want.', 'reference': 'Psalm 23:1'},
    {'text': 'For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.', 'reference': 'John 3:16'},
    {'text': 'Trust in the Lord with all thine heart; and lean not unto thine own understanding.', 'reference': 'Proverbs 3:5'},
    {'text': 'I can do all things through Christ which strengtheneth me.', 'reference': 'Philippians 4:13'},
    {'text': 'The Lord is my light and my salvation; whom shall I fear? The Lord is the strength of my life; of whom shall I be afraid?', 'reference': 'Psalm 27:1'},
    {'text': 'And we know that all things work together for good to them that love God, to them who are the called according to his purpose.', 'reference': 'Romans 8:28'},
    {'text': 'Be strong and of a good courage; be not afraid, neither be thou dismayed: for the Lord thy God is with thee whithersoever thou goest.', 'reference': 'Joshua 1:9'},
    {'text': 'For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.', 'reference': 'Jeremiah 29:11'},
    {'text': 'The Lord bless thee, and keep thee: The Lord make his face shine upon thee, and be gracious unto thee.', 'reference': 'Numbers 6:24-25'},
    {'text': 'But they that wait upon the Lord shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.', 'reference': 'Isaiah 40:31'},

    // Day 11-20
    {'text': 'Come unto me, all ye that labour and are heavy laden, and I will give you rest.', 'reference': 'Matthew 11:28'},
    {'text': 'The Lord is near to the brokenhearted and saves the crushed in spirit.', 'reference': 'Psalm 34:18'},
    {'text': 'Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee.', 'reference': 'Isaiah 41:10'},
    {'text': 'Delight thyself also in the Lord; and he shall give thee the desires of thine heart.', 'reference': 'Psalm 37:4'},
    {'text': 'Jesus said unto him, I am the way, the truth, and the life: no man cometh unto the Father, but by me.', 'reference': 'John 14:6'},
    {'text': 'Be still, and know that I am God.', 'reference': 'Psalm 46:10'},
    {'text': 'For by grace are ye saved through faith; and that not of yourselves: it is the gift of God.', 'reference': 'Ephesians 2:8'},
    {'text': 'The grass withereth, the flower fadeth: but the word of our God shall stand for ever.', 'reference': 'Isaiah 40:8'},
    {'text': 'Cast all your anxiety on him because he cares for you.', 'reference': '1 Peter 5:7'},
    {'text': 'Create in me a clean heart, O God; and renew a right spirit within me.', 'reference': 'Psalm 51:10'},

    // Day 21-30
    {'text': 'But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith, meekness, temperance.', 'reference': 'Galatians 5:22-23'},
    {'text': 'God is our refuge and strength, a very present help in trouble.', 'reference': 'Psalm 46:1'},
    {'text': 'And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.', 'reference': 'Philippians 4:7'},
    {'text': 'If God be for us, who can be against us?', 'reference': 'Romans 8:31'},
    {'text': 'Thy word is a lamp unto my feet, and a light unto my path.', 'reference': 'Psalm 119:105'},
    {'text': 'But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.', 'reference': 'Matthew 6:33'},
    {'text': 'He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty.', 'reference': 'Psalm 91:1'},
    {'text': 'For where two or three are gathered together in my name, there am I in the midst of them.', 'reference': 'Matthew 18:20'},
    {'text': 'The Lord is my strength and my shield; my heart trusted in him, and I am helped.', 'reference': 'Psalm 28:7'},
    {'text': 'No weapon that is formed against thee shall prosper.', 'reference': 'Isaiah 54:17'},

    // Day 31-40
    {'text': 'Jesus Christ the same yesterday, and to day, and for ever.', 'reference': 'Hebrews 13:8'},
    {'text': 'Blessed is the man that trusteth in the Lord, and whose hope the Lord is.', 'reference': 'Jeremiah 17:7'},
    {'text': 'He maketh me to lie down in green pastures: he leadeth me beside the still waters.', 'reference': 'Psalm 23:2'},
    {'text': 'And my God will meet all your needs according to the riches of his glory in Christ Jesus.', 'reference': 'Philippians 4:19'},
    {'text': 'Have not I commanded thee? Be strong and of a good courage.', 'reference': 'Joshua 1:9'},
    {'text': 'The name of the Lord is a strong tower: the righteous runneth into it, and is safe.', 'reference': 'Proverbs 18:10'},
    {'text': 'For with God nothing shall be impossible.', 'reference': 'Luke 1:37'},
    {'text': 'He healeth the broken in heart, and bindeth up their wounds.', 'reference': 'Psalm 147:3'},
    {'text': 'Draw nigh to God, and he will draw nigh to you.', 'reference': 'James 4:8'},
    {'text': 'A new commandment I give unto you, That ye love one another; as I have loved you.', 'reference': 'John 13:34'},

    // Day 41-50
    {'text': 'In all thy ways acknowledge him, and he shall direct thy paths.', 'reference': 'Proverbs 3:6'},
    {'text': 'The Lord is gracious, and full of compassion; slow to anger, and of great mercy.', 'reference': 'Psalm 145:8'},
    {'text': 'Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you.', 'reference': 'John 14:27'},
    {'text': 'For we walk by faith, not by sight.', 'reference': '2 Corinthians 5:7'},
    {'text': 'I will lift up mine eyes unto the hills, from whence cometh my help. My help cometh from the Lord.', 'reference': 'Psalm 121:1-2'},
    {'text': 'Beloved, let us love one another: for love is of God; and every one that loveth is born of God, and knoweth God.', 'reference': '1 John 4:7'},
    {'text': 'The joy of the Lord is your strength.', 'reference': 'Nehemiah 8:10'},
    {'text': 'If we confess our sins, he is faithful and just to forgive us our sins, and to cleanse us from all unrighteousness.', 'reference': '1 John 1:9'},
    {'text': 'But God commendeth his love toward us, in that, while we were yet sinners, Christ died for us.', 'reference': 'Romans 5:8'},
    {'text': 'This is the day which the Lord hath made; we will rejoice and be glad in it.', 'reference': 'Psalm 118:24'},

    // Day 51-60
    {'text': 'He restoreth my soul: he leadeth me in the paths of righteousness for his name\'s sake.', 'reference': 'Psalm 23:3'},
    {'text': 'Therefore, if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new.', 'reference': '2 Corinthians 5:17'},
    {'text': 'For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.', 'reference': '2 Timothy 1:7'},
    {'text': 'The earth is the Lord\'s, and the fulness thereof; the world, and they that dwell therein.', 'reference': 'Psalm 24:1'},
    {'text': 'Be ye kind one to another, tenderhearted, forgiving one another, even as God for Christ\'s sake hath forgiven you.', 'reference': 'Ephesians 4:32'},
    {'text': 'I have told you these things, so that in me you may have peace. In this world you will have trouble. But take heart! I have overcome the world.', 'reference': 'John 16:33'},
    {'text': 'Bless the Lord, O my soul: and all that is within me, bless his holy name.', 'reference': 'Psalm 103:1'},
    {'text': 'Now faith is the substance of things hoped for, the evidence of things not seen.', 'reference': 'Hebrews 11:1'},
    {'text': 'The Lord is good, a strong hold in the day of trouble; and he knoweth them that trust in him.', 'reference': 'Nahum 1:7'},
    {'text': 'Love is patient, love is kind. It does not envy, it does not boast, it is not proud.', 'reference': '1 Corinthians 13:4'},

    // Day 61-70
    {'text': 'Commit thy way unto the Lord; trust also in him; and he shall bring it to pass.', 'reference': 'Psalm 37:5'},
    {'text': 'I am the vine, ye are the branches: He that abideth in me, and I in him, the same bringeth forth much fruit.', 'reference': 'John 15:5'},
    {'text': 'He shall cover thee with his feathers, and under his wings shalt thou trust.', 'reference': 'Psalm 91:4'},
    {'text': 'And let the peace of God rule in your hearts, to the which also ye are called in one body; and be ye thankful.', 'reference': 'Colossians 3:15'},
    {'text': 'O taste and see that the Lord is good: blessed is the man that trusteth in him.', 'reference': 'Psalm 34:8'},
    {'text': 'Be not overcome of evil, but overcome evil with good.', 'reference': 'Romans 12:21'},
    {'text': 'Behold, I stand at the door, and knock: if any man hear my voice, and open the door, I will come in to him.', 'reference': 'Revelation 3:20'},
    {'text': 'Great is the Lord, and greatly to be praised; and his greatness is unsearchable.', 'reference': 'Psalm 145:3'},
    {'text': 'Rejoice in the Lord always: and again I say, Rejoice.', 'reference': 'Philippians 4:4'},
    {'text': 'The Lord thy God in the midst of thee is mighty; he will save, he will rejoice over thee with joy.', 'reference': 'Zephaniah 3:17'},

    // Day 71-80
    {'text': 'Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me.', 'reference': 'Psalm 23:4'},
    {'text': 'Not by might, nor by power, but by my spirit, saith the Lord of hosts.', 'reference': 'Zechariah 4:6'},
    {'text': 'If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not.', 'reference': 'James 1:5'},
    {'text': 'The Lord is faithful, who shall stablish you, and keep you from evil.', 'reference': '2 Thessalonians 3:3'},
    {'text': 'As the hart panteth after the water brooks, so panteth my soul after thee, O God.', 'reference': 'Psalm 42:1'},
    {'text': 'Greater is he that is in you, than he that is in the world.', 'reference': '1 John 4:4'},
    {'text': 'Every good gift and every perfect gift is from above, and cometh down from the Father of lights.', 'reference': 'James 1:17'},
    {'text': 'I will praise thee; for I am fearfully and wonderfully made: marvellous are thy works.', 'reference': 'Psalm 139:14'},
    {'text': 'Blessed are the pure in heart: for they shall see God.', 'reference': 'Matthew 5:8'},
    {'text': 'He that covereth his sins shall not prosper: but whoso confesseth and forsaketh them shall have mercy.', 'reference': 'Proverbs 28:13'},

    // Day 81-90
    {'text': 'I have been crucified with Christ; it is no longer I who live, but Christ lives in me.', 'reference': 'Galatians 2:20'},
    {'text': 'O Lord, thou art my God; I will exalt thee, I will praise thy name; for thou hast done wonderful things.', 'reference': 'Isaiah 25:1'},
    {'text': 'Thou preparest a table before me in the presence of mine enemies: thou anointest my head with oil; my cup runneth over.', 'reference': 'Psalm 23:5'},
    {'text': 'Blessed are the peacemakers: for they shall be called the children of God.', 'reference': 'Matthew 5:9'},
    {'text': 'Wherefore take unto you the whole armour of God, that ye may be able to withstand in the evil day.', 'reference': 'Ephesians 6:13'},
    {'text': 'The steps of a good man are ordered by the Lord: and he delighteth in his way.', 'reference': 'Psalm 37:23'},
    {'text': 'I am the resurrection, and the life: he that believeth in me, though he were dead, yet shall he live.', 'reference': 'John 11:25'},
    {'text': 'In the beginning God created the heaven and the earth.', 'reference': 'Genesis 1:1'},
    {'text': 'Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up.', 'reference': 'Galatians 6:9'},
    {'text': 'Wait on the Lord: be of good courage, and he shall strengthen thine heart.', 'reference': 'Psalm 27:14'},

    // Day 91-100
    {'text': 'For the wages of sin is death; but the gift of God is eternal life through Jesus Christ our Lord.', 'reference': 'Romans 6:23'},
    {'text': 'The heavens declare the glory of God; and the firmament sheweth his handywork.', 'reference': 'Psalm 19:1'},
    {'text': 'I am the good shepherd: the good shepherd giveth his life for the sheep.', 'reference': 'John 10:11'},
    {'text': 'A soft answer turneth away wrath: but grievous words stir up anger.', 'reference': 'Proverbs 15:1'},
    {'text': 'Who shall separate us from the love of Christ? Shall tribulation, or distress, or persecution, or famine?', 'reference': 'Romans 8:35'},
    {'text': 'Let the words of my mouth, and the meditation of my heart, be acceptable in thy sight, O Lord.', 'reference': 'Psalm 19:14'},
    {'text': 'I am the bread of life: he that cometh to me shall never hunger; and he that believeth on me shall never thirst.', 'reference': 'John 6:35'},
    {'text': 'The fear of the Lord is the beginning of wisdom: and the knowledge of the holy is understanding.', 'reference': 'Proverbs 9:10'},
    {'text': 'Surely goodness and mercy shall follow me all the days of my life: and I will dwell in the house of the Lord for ever.', 'reference': 'Psalm 23:6'},
    {'text': 'Therefore being justified by faith, we have peace with God through our Lord Jesus Christ.', 'reference': 'Romans 5:1'},

    // Day 101-110
    {'text': 'Have I not commanded you? Be strong and courageous. Do not be afraid; do not be discouraged.', 'reference': 'Joshua 1:9'},
    {'text': 'I will never leave thee, nor forsake thee.', 'reference': 'Hebrews 13:5'},
    {'text': 'The Lord is close to the brokenhearted and saves those who are crushed in spirit.', 'reference': 'Psalm 34:18'},
    {'text': 'Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you.', 'reference': 'Matthew 7:7'},
    {'text': 'He giveth power to the faint; and to them that have no might he increaseth strength.', 'reference': 'Isaiah 40:29'},
    {'text': 'Blessed is the man that walketh not in the counsel of the ungodly, nor standeth in the way of sinners.', 'reference': 'Psalm 1:1'},
    {'text': 'And be not conformed to this world: but be ye transformed by the renewing of your mind.', 'reference': 'Romans 12:2'},
    {'text': 'He that hath the Son hath life; and he that hath not the Son of God hath not life.', 'reference': '1 John 5:12'},
    {'text': 'I sought the Lord, and he heard me, and delivered me from all my fears.', 'reference': 'Psalm 34:4'},
    {'text': 'But as many as received him, to them gave he power to become the sons of God.', 'reference': 'John 1:12'},

    // Day 111-120
    {'text': 'Train up a child in the way he should go: and when he is old, he will not depart from it.', 'reference': 'Proverbs 22:6'},
    {'text': 'The Lord shall preserve thee from all evil: he shall preserve thy soul.', 'reference': 'Psalm 121:7'},
    {'text': 'And whatsoever ye do, do it heartily, as to the Lord, and not unto men.', 'reference': 'Colossians 3:23'},
    {'text': 'Casting all your care upon him; for he careth for you.', 'reference': '1 Peter 5:7'},
    {'text': 'He that is slow to anger is better than the mighty; and he that ruleth his spirit than he that taketh a city.', 'reference': 'Proverbs 16:32'},
    {'text': 'Praise ye the Lord. Praise God in his sanctuary: praise him in the firmament of his power.', 'reference': 'Psalm 150:1'},
    {'text': 'There is therefore now no condemnation to them which are in Christ Jesus.', 'reference': 'Romans 8:1'},
    {'text': 'I am the light of the world: he that followeth me shall not walk in darkness, but shall have the light of life.', 'reference': 'John 8:12'},
    {'text': 'The Lord is my rock, and my fortress, and my deliverer; my God, my strength, in whom I will trust.', 'reference': 'Psalm 18:2'},
    {'text': 'Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.', 'reference': 'Philippians 4:6'},

    // Day 121-130
    {'text': 'For thou art my rock and my fortress; therefore for thy name\'s sake lead me, and guide me.', 'reference': 'Psalm 31:3'},
    {'text': 'In him was life; and the life was the light of men.', 'reference': 'John 1:4'},
    {'text': 'A friend loveth at all times, and a brother is born for adversity.', 'reference': 'Proverbs 17:17'},
    {'text': 'The Lord is the strength of my life; of whom shall I be afraid?', 'reference': 'Psalm 27:1'},
    {'text': 'But God, who is rich in mercy, for his great love wherewith he loved us.', 'reference': 'Ephesians 2:4'},
    {'text': 'Abide in me, and I in you. As the branch cannot bear fruit of itself, except it abide in the vine.', 'reference': 'John 15:4'},
    {'text': 'Many are the afflictions of the righteous: but the Lord delivereth him out of them all.', 'reference': 'Psalm 34:19'},
    {'text': 'Set your affection on things above, not on things on the earth.', 'reference': 'Colossians 3:2'},
    {'text': 'The Lord will fight for you, and you shall hold your peace.', 'reference': 'Exodus 14:14'},
    {'text': 'Enter into his gates with thanksgiving, and into his courts with praise: be thankful unto him, and bless his name.', 'reference': 'Psalm 100:4'},

    // Day 131-140
    {'text': 'And Jesus said unto them, I am the bread of life: he that cometh to me shall never hunger.', 'reference': 'John 6:35'},
    {'text': 'Above all, love each other deeply, because love covers over a multitude of sins.', 'reference': '1 Peter 4:8'},
    {'text': 'In God I will praise his word, in God I have put my trust; I will not fear what flesh can do unto me.', 'reference': 'Psalm 56:4'},
    {'text': 'The thief cometh not, but for to steal, and to kill, and to destroy: I am come that they might have life, and have it more abundantly.', 'reference': 'John 10:10'},
    {'text': 'A merry heart doeth good like a medicine: but a broken spirit drieth the bones.', 'reference': 'Proverbs 17:22'},
    {'text': 'From the rising of the sun unto the going down of the same the Lord\'s name is to be praised.', 'reference': 'Psalm 113:3'},
    {'text': 'For where your treasure is, there will your heart be also.', 'reference': 'Matthew 6:21'},
    {'text': 'Being confident of this very thing, that he which hath begun a good work in you will perform it until the day of Jesus Christ.', 'reference': 'Philippians 1:6'},
    {'text': 'How precious also are thy thoughts unto me, O God! How great is the sum of them!', 'reference': 'Psalm 139:17'},
    {'text': 'But my God shall supply all your need according to his riches in glory by Christ Jesus.', 'reference': 'Philippians 4:19'},

    // Day 141-150
    {'text': 'For the Lord God is a sun and shield: the Lord will give grace and glory.', 'reference': 'Psalm 84:11'},
    {'text': 'If ye abide in me, and my words abide in you, ye shall ask what ye will, and it shall be done unto you.', 'reference': 'John 15:7'},
    {'text': 'And above all these things put on charity, which is the bond of perfectness.', 'reference': 'Colossians 3:14'},
    {'text': 'He brought me up also out of an horrible pit, out of the miry clay, and set my feet upon a rock.', 'reference': 'Psalm 40:2'},
    {'text': 'For the Lord giveth wisdom: out of his mouth cometh knowledge and understanding.', 'reference': 'Proverbs 2:6'},
    {'text': 'There is no fear in love; but perfect love casteth out fear.', 'reference': '1 John 4:18'},
    {'text': 'Whom have I in heaven but thee? And there is none upon earth that I desire beside thee.', 'reference': 'Psalm 73:25'},
    {'text': 'And we know that the Son of God is come, and hath given us an understanding, that we may know him that is true.', 'reference': '1 John 5:20'},
    {'text': 'He that handleth a matter wisely shall find good: and whoso trusteth in the Lord, happy is he.', 'reference': 'Proverbs 16:20'},
    {'text': 'Make a joyful noise unto the Lord, all ye lands. Serve the Lord with gladness.', 'reference': 'Psalm 100:1-2'},

    // Day 151-160
    {'text': 'I am with you always, even unto the end of the world.', 'reference': 'Matthew 28:20'},
    {'text': 'For as the heavens are higher than the earth, so are my ways higher than your ways, and my thoughts than your thoughts.', 'reference': 'Isaiah 55:9'},
    {'text': 'The Lord is my portion, saith my soul; therefore will I hope in him.', 'reference': 'Lamentations 3:24'},
    {'text': 'For we are his workmanship, created in Christ Jesus unto good works.', 'reference': 'Ephesians 2:10'},
    {'text': 'He that keepeth thee will not slumber.', 'reference': 'Psalm 121:3'},
    {'text': 'If the Son therefore shall make you free, ye shall be free indeed.', 'reference': 'John 8:36'},
    {'text': 'Keep thy heart with all diligence; for out of it are the issues of life.', 'reference': 'Proverbs 4:23'},
    {'text': 'It is of the Lord\'s mercies that we are not consumed, because his compassions fail not. They are new every morning.', 'reference': 'Lamentations 3:22-23'},
    {'text': 'Blessed are they which do hunger and thirst after righteousness: for they shall be filled.', 'reference': 'Matthew 5:6'},
    {'text': 'The Lord hath done great things for us; whereof we are glad.', 'reference': 'Psalm 126:3'},

    // Day 161-170
    {'text': 'Neither death, nor life, nor angels, nor principalities, nor powers shall be able to separate us from the love of God.', 'reference': 'Romans 8:38-39'},
    {'text': 'I will say of the Lord, He is my refuge and my fortress: my God; in him will I trust.', 'reference': 'Psalm 91:2'},
    {'text': 'Let all that you do be done in love.', 'reference': '1 Corinthians 16:14'},
    {'text': 'The Lord is righteous in all his ways, and holy in all his works.', 'reference': 'Psalm 145:17'},
    {'text': 'For the word of God is quick, and powerful, and sharper than any twoedged sword.', 'reference': 'Hebrews 4:12'},
    {'text': 'So then faith cometh by hearing, and hearing by the word of God.', 'reference': 'Romans 10:17'},
    {'text': 'My grace is sufficient for thee: for my strength is made perfect in weakness.', 'reference': '2 Corinthians 12:9'},
    {'text': 'I waited patiently for the Lord; and he inclined unto me, and heard my cry.', 'reference': 'Psalm 40:1'},
    {'text': 'But the Comforter, which is the Holy Ghost, whom the Father will send in my name, he shall teach you all things.', 'reference': 'John 14:26'},
    {'text': 'Pleasant words are as an honeycomb, sweet to the soul, and health to the bones.', 'reference': 'Proverbs 16:24'},

    // Day 171-180
    {'text': 'As for God, his way is perfect: the word of the Lord is tried: he is a buckler to all those that trust in him.', 'reference': 'Psalm 18:30'},
    {'text': 'Whatsoever ye shall ask in my name, that will I do, that the Father may be glorified in the Son.', 'reference': 'John 14:13'},
    {'text': 'The Lord is nigh unto all them that call upon him, to all that call upon him in truth.', 'reference': 'Psalm 145:18'},
    {'text': 'Humble yourselves therefore under the mighty hand of God, that he may exalt you in due time.', 'reference': '1 Peter 5:6'},
    {'text': 'And God is able to make all grace abound toward you; that ye, always having all sufficiency in all things, may abound to every good work.', 'reference': '2 Corinthians 9:8'},
    {'text': 'O give thanks unto the Lord; for he is good: for his mercy endureth for ever.', 'reference': 'Psalm 136:1'},
    {'text': 'For I am persuaded, that neither death, nor life, nor angels, nor principalities, nor powers, nor things present, nor things to come, shall be able to separate us from the love of God.', 'reference': 'Romans 8:38-39'},
    {'text': 'Teach me thy way, O Lord; I will walk in thy truth: unite my heart to fear thy name.', 'reference': 'Psalm 86:11'},
    {'text': 'And we have known and believed the love that God hath to us. God is love; and he that dwelleth in love dwelleth in God.', 'reference': '1 John 4:16'},
    {'text': 'He that getteth wisdom loveth his own soul: he that keepeth understanding shall find good.', 'reference': 'Proverbs 19:8'},

    // Day 181-190
    {'text': 'O Lord, how manifold are thy works! In wisdom hast thou made them all: the earth is full of thy riches.', 'reference': 'Psalm 104:24'},
    {'text': 'I have set the Lord always before me: because he is at my right hand, I shall not be moved.', 'reference': 'Psalm 16:8'},
    {'text': 'But ye shall receive power, after that the Holy Ghost is come upon you.', 'reference': 'Acts 1:8'},
    {'text': 'The fear of the Lord is the beginning of knowledge: but fools despise wisdom and instruction.', 'reference': 'Proverbs 1:7'},
    {'text': 'Blessed be the God and Father of our Lord Jesus Christ, who hath blessed us with all spiritual blessings in heavenly places in Christ.', 'reference': 'Ephesians 1:3'},
    {'text': 'O come, let us worship and bow down: let us kneel before the Lord our maker.', 'reference': 'Psalm 95:6'},
    {'text': 'He must increase, but I must decrease.', 'reference': 'John 3:30'},
    {'text': 'Though he fall, he shall not be utterly cast down: for the Lord upholdeth him with his hand.', 'reference': 'Psalm 37:24'},
    {'text': 'Bear ye one another\'s burdens, and so fulfil the law of Christ.', 'reference': 'Galatians 6:2'},
    {'text': 'But the Lord is faithful, who shall stablish you, and keep you from evil.', 'reference': '2 Thessalonians 3:3'},

    // Day 191-200
    {'text': 'Give thanks unto the Lord, call upon his name, make known his deeds among the people.', 'reference': 'Psalm 105:1'},
    {'text': 'Herein is love, not that we loved God, but that he loved us, and sent his Son to be the propitiation for our sins.', 'reference': '1 John 4:10'},
    {'text': 'Thou wilt keep him in perfect peace, whose mind is stayed on thee: because he trusteth in thee.', 'reference': 'Isaiah 26:3'},
    {'text': 'I will bless the Lord at all times: his praise shall continually be in my mouth.', 'reference': 'Psalm 34:1'},
    {'text': 'For to me to live is Christ, and to die is gain.', 'reference': 'Philippians 1:21'},
    {'text': 'O Lord, thou hast searched me, and known me. Thou knowest my downsitting and mine uprising.', 'reference': 'Psalm 139:1-2'},
    {'text': 'Grace and peace be multiplied unto you through the knowledge of God, and of Jesus our Lord.', 'reference': '2 Peter 1:2'},
    {'text': 'He shall call upon me, and I will answer him: I will be with him in trouble; I will deliver him, and honour him.', 'reference': 'Psalm 91:15'},
    {'text': 'The Lord your God is in your midst, a mighty one who will save.', 'reference': 'Zephaniah 3:17'},
    {'text': 'But grow in grace, and in the knowledge of our Lord and Saviour Jesus Christ.', 'reference': '2 Peter 3:18'},

    // Day 201-210
    {'text': 'The Lord shall preserve thy going out and thy coming in from this time forth, and even for evermore.', 'reference': 'Psalm 121:8'},
    {'text': 'For God is not the author of confusion, but of peace.', 'reference': '1 Corinthians 14:33'},
    {'text': 'And the Lord, he it is that doth go before thee; he will be with thee, he will not fail thee, neither forsake thee.', 'reference': 'Deuteronomy 31:8'},
    {'text': 'I will praise the name of God with a song, and will magnify him with thanksgiving.', 'reference': 'Psalm 69:30'},
    {'text': 'Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost.', 'reference': 'Romans 15:13'},
    {'text': 'The Lord also will be a refuge for the oppressed, a refuge in times of trouble.', 'reference': 'Psalm 9:9'},
    {'text': 'That if thou shalt confess with thy mouth the Lord Jesus, and shalt believe in thine heart that God hath raised him from the dead, thou shalt be saved.', 'reference': 'Romans 10:9'},
    {'text': 'As far as the east is from the west, so far hath he removed our transgressions from us.', 'reference': 'Psalm 103:12'},
    {'text': 'And let us consider one another to provoke unto love and to good works.', 'reference': 'Hebrews 10:24'},
    {'text': 'Look at the birds of the air; they do not sow or reap or store away in barns, and yet your heavenly Father feeds them.', 'reference': 'Matthew 6:26'},

    // Day 211-220
    {'text': 'Whom have I in heaven but thee? And there is none upon earth that I desire beside thee. My flesh and my heart faileth: but God is the strength of my heart.', 'reference': 'Psalm 73:25-26'},
    {'text': 'And the work of righteousness shall be peace; and the effect of righteousness quietness and assurance for ever.', 'reference': 'Isaiah 32:17'},
    {'text': 'Blessed is he whose transgression is forgiven, whose sin is covered.', 'reference': 'Psalm 32:1'},
    {'text': 'Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.', 'reference': 'Philippians 4:6'},
    {'text': 'And thou shalt love the Lord thy God with all thine heart, and with all thy soul, and with all thy might.', 'reference': 'Deuteronomy 6:5'},
    {'text': 'My soul, wait thou only upon God; for my expectation is from him.', 'reference': 'Psalm 62:5'},
    {'text': 'For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.', 'reference': '2 Timothy 1:7'},
    {'text': 'Blessed are the merciful: for they shall obtain mercy.', 'reference': 'Matthew 5:7'},
    {'text': 'Show me thy ways, O Lord; teach me thy paths.', 'reference': 'Psalm 25:4'},
    {'text': 'And whatsoever ye do in word or deed, do all in the name of the Lord Jesus, giving thanks to God and the Father by him.', 'reference': 'Colossians 3:17'},

    // Day 221-230
    {'text': 'Because he hath set his love upon me, therefore will I deliver him: I will set him on high, because he hath known my name.', 'reference': 'Psalm 91:14'},
    {'text': 'He hath shewed thee, O man, what is good; and what doth the Lord require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?', 'reference': 'Micah 6:8'},
    {'text': 'And be ye kind one to another, tenderhearted, forgiving one another, even as God for Christ\'s sake hath forgiven you.', 'reference': 'Ephesians 4:32'},
    {'text': 'When thou passest through the waters, I will be with thee; and through the rivers, they shall not overflow thee.', 'reference': 'Isaiah 43:2'},
    {'text': 'It is good for me that I have been afflicted; that I might learn thy statutes.', 'reference': 'Psalm 119:71'},
    {'text': 'I press toward the mark for the prize of the high calling of God in Christ Jesus.', 'reference': 'Philippians 3:14'},
    {'text': 'Lift up your heads, O ye gates; and be ye lift up, ye everlasting doors; and the King of glory shall come in.', 'reference': 'Psalm 24:7'},
    {'text': 'But the wisdom that is from above is first pure, then peaceable, gentle, and easy to be intreated, full of mercy and good fruits.', 'reference': 'James 3:17'},
    {'text': 'He hath made every thing beautiful in his time: also he hath set the world in their heart.', 'reference': 'Ecclesiastes 3:11'},
    {'text': 'Sing unto the Lord a new song, and his praise from the end of the earth.', 'reference': 'Isaiah 42:10'},

    // Day 231-240
    {'text': 'The Lord will give strength unto his people; the Lord will bless his people with peace.', 'reference': 'Psalm 29:11'},
    {'text': 'If ye then, being evil, know how to give good gifts unto your children, how much more shall your Father which is in heaven give good things to them that ask him?', 'reference': 'Matthew 7:11'},
    {'text': 'Blessed are they that keep his testimonies, and that seek him with the whole heart.', 'reference': 'Psalm 119:2'},
    {'text': 'And the Lord shall guide thee continually, and satisfy thy soul in drought.', 'reference': 'Isaiah 58:11'},
    {'text': 'Seeing then that we have a great high priest, that is passed into the heavens, Jesus the Son of God, let us hold fast our profession.', 'reference': 'Hebrews 4:14'},
    {'text': 'He hath put a new song in my mouth, even praise unto our God: many shall see it, and fear, and shall trust in the Lord.', 'reference': 'Psalm 40:3'},
    {'text': 'For I the Lord thy God will hold thy right hand, saying unto thee, Fear not; I will help thee.', 'reference': 'Isaiah 41:13'},
    {'text': 'Let us therefore come boldly unto the throne of grace, that we may obtain mercy, and find grace to help in time of need.', 'reference': 'Hebrews 4:16'},
    {'text': 'Bless the Lord, O my soul, and forget not all his benefits.', 'reference': 'Psalm 103:2'},
    {'text': 'Give, and it shall be given unto you; good measure, pressed down, and shaken together, and running over.', 'reference': 'Luke 6:38'},

    // Day 241-250
    {'text': 'I will instruct thee and teach thee in the way which thou shalt go: I will guide thee with mine eye.', 'reference': 'Psalm 32:8'},
    {'text': 'That Christ may dwell in your hearts by faith; that ye, being rooted and grounded in love.', 'reference': 'Ephesians 3:17'},
    {'text': 'O Lord my God, I cried unto thee, and thou hast healed me.', 'reference': 'Psalm 30:2'},
    {'text': 'Come now, and let us reason together, saith the Lord: though your sins be as scarlet, they shall be as white as snow.', 'reference': 'Isaiah 1:18'},
    {'text': 'Strengthened with all might, according to his glorious power, unto all patience and longsuffering with joyfulness.', 'reference': 'Colossians 1:11'},
    {'text': 'Praise the Lord. How good it is to sing praises to our God, how pleasant and fitting to praise him.', 'reference': 'Psalm 147:1'},
    {'text': 'And all things, whatsoever ye shall ask in prayer, believing, ye shall receive.', 'reference': 'Matthew 21:22'},
    {'text': 'The Lord taketh pleasure in them that fear him, in those that hope in his mercy.', 'reference': 'Psalm 147:11'},
    {'text': 'Wherefore seeing we also are compassed about with so great a cloud of witnesses, let us run with patience the race that is set before us.', 'reference': 'Hebrews 12:1'},
    {'text': 'To every thing there is a season, and a time to every purpose under the heaven.', 'reference': 'Ecclesiastes 3:1'},

    // Day 251-260
    {'text': 'Praise ye the Lord. O give thanks unto the Lord; for he is good: for his mercy endureth for ever.', 'reference': 'Psalm 106:1'},
    {'text': 'And Jesus looking upon them saith, With men it is impossible, but not with God: for with God all things are possible.', 'reference': 'Mark 10:27'},
    {'text': 'The Lord openeth the eyes of the blind: the Lord raiseth them that are bowed down: the Lord loveth the righteous.', 'reference': 'Psalm 146:8'},
    {'text': 'Brethren, I count not myself to have apprehended: but this one thing I do, forgetting those things which are behind, and reaching forth unto those things which are before.', 'reference': 'Philippians 3:13'},
    {'text': 'Trust in him at all times; ye people, pour out your heart before him: God is a refuge for us.', 'reference': 'Psalm 62:8'},
    {'text': 'Remember ye not the former things, neither consider the things of old. Behold, I will do a new thing.', 'reference': 'Isaiah 43:18-19'},
    {'text': 'Put on the whole armour of God, that ye may be able to stand against the wiles of the devil.', 'reference': 'Ephesians 6:11'},
    {'text': 'Great peace have they which love thy law: and nothing shall offend them.', 'reference': 'Psalm 119:165'},
    {'text': 'If we live in the Spirit, let us also walk in the Spirit.', 'reference': 'Galatians 5:25'},
    {'text': 'Then they cried unto the Lord in their trouble, and he delivered them out of their distresses.', 'reference': 'Psalm 107:6'},

    // Day 261-270
    {'text': 'Looking unto Jesus the author and finisher of our faith.', 'reference': 'Hebrews 12:2'},
    {'text': 'I will extol thee, my God, O king; and I will bless thy name for ever and ever.', 'reference': 'Psalm 145:1'},
    {'text': 'And the God of all grace, who called you to his eternal glory in Christ, after you have suffered a little while, will himself restore you and make you strong.', 'reference': '1 Peter 5:10'},
    {'text': 'How sweet are thy words unto my taste! Yea, sweeter than honey to my mouth!', 'reference': 'Psalm 119:103'},
    {'text': 'Behold, what manner of love the Father hath bestowed upon us, that we should be called the sons of God.', 'reference': '1 John 3:1'},
    {'text': 'The righteous cry, and the Lord heareth, and delivereth them out of all their troubles.', 'reference': 'Psalm 34:17'},
    {'text': 'I have been young, and now am old; yet have I not seen the righteous forsaken, nor his seed begging bread.', 'reference': 'Psalm 37:25'},
    {'text': 'With long life will I satisfy him, and shew him my salvation.', 'reference': 'Psalm 91:16'},
    {'text': 'For the Lord God will help me; therefore shall I not be confounded.', 'reference': 'Isaiah 50:7'},
    {'text': 'Now unto him that is able to do exceeding abundantly above all that we ask or think, according to the power that worketh in us.', 'reference': 'Ephesians 3:20'},

    // Day 271-280
    {'text': 'I will sing unto the Lord, because he hath dealt bountifully with me.', 'reference': 'Psalm 13:6'},
    {'text': 'And this is the confidence that we have in him, that, if we ask any thing according to his will, he heareth us.', 'reference': '1 John 5:14'},
    {'text': 'For the Lord most high is terrible; he is a great King over all the earth.', 'reference': 'Psalm 47:2'},
    {'text': 'The Lord is on my side; I will not fear: what can man do unto me?', 'reference': 'Psalm 118:6'},
    {'text': 'Finally, brethren, whatsoever things are true, whatsoever things are honest, whatsoever things are just, whatsoever things are pure, whatsoever things are lovely, think on these things.', 'reference': 'Philippians 4:8'},
    {'text': 'Because thy lovingkindness is better than life, my lips shall praise thee.', 'reference': 'Psalm 63:3'},
    {'text': 'But the God of all grace, who hath called us unto his eternal glory by Christ Jesus, after that ye have suffered a while, make you perfect, stablish, strengthen, settle you.', 'reference': '1 Peter 5:10'},
    {'text': 'Hear, O Lord, when I cry with my voice: have mercy also upon me, and answer me.', 'reference': 'Psalm 27:7'},
    {'text': 'For in him we live, and move, and have our being.', 'reference': 'Acts 17:28'},
    {'text': 'The Lord is my helper, and I will not fear what man shall do unto me.', 'reference': 'Hebrews 13:6'},

    // Day 281-290
    {'text': 'I love the Lord, because he hath heard my voice and my supplications.', 'reference': 'Psalm 116:1'},
    {'text': 'But they that seek the Lord shall not want any good thing.', 'reference': 'Psalm 34:10'},
    {'text': 'By this shall all men know that ye are my disciples, if ye have love one to another.', 'reference': 'John 13:35'},
    {'text': 'For thou, Lord, art good, and ready to forgive; and plenteous in mercy unto all them that call upon thee.', 'reference': 'Psalm 86:5'},
    {'text': 'And he said unto me, My grace is sufficient for thee: for my strength is made perfect in weakness.', 'reference': '2 Corinthians 12:9'},
    {'text': 'For the Lord your God is gracious and merciful, and will not turn away his face from you, if ye return unto him.', 'reference': '2 Chronicles 30:9'},
    {'text': 'Return unto thy rest, O my soul; for the Lord hath dealt bountifully with thee.', 'reference': 'Psalm 116:7'},
    {'text': 'But unto you that fear my name shall the Sun of righteousness arise with healing in his wings.', 'reference': 'Malachi 4:2'},
    {'text': 'In my distress I cried unto the Lord, and he heard me.', 'reference': 'Psalm 120:1'},
    {'text': 'But ye are a chosen generation, a royal priesthood, an holy nation, a peculiar people.', 'reference': '1 Peter 2:9'},

    // Day 291-300
    {'text': 'I will both lay me down in peace, and sleep: for thou, Lord, only makest me dwell in safety.', 'reference': 'Psalm 4:8'},
    {'text': 'If ye love me, keep my commandments.', 'reference': 'John 14:15'},
    {'text': 'In thee, O Lord, do I put my trust; let me never be ashamed: deliver me in thy righteousness.', 'reference': 'Psalm 31:1'},
    {'text': 'And let us not be weary in well doing: for in due season we shall reap, if we faint not.', 'reference': 'Galatians 6:9'},
    {'text': 'My soul shall be satisfied as with marrow and fatness; and my mouth shall praise thee with joyful lips.', 'reference': 'Psalm 63:5'},
    {'text': 'He that believeth on the Son hath everlasting life.', 'reference': 'John 3:36'},
    {'text': 'Lead me in thy truth, and teach me: for thou art the God of my salvation; on thee do I wait all the day.', 'reference': 'Psalm 25:5'},
    {'text': 'Know ye that the Lord he is God: it is he that hath made us, and not we ourselves; we are his people, and the sheep of his pasture.', 'reference': 'Psalm 100:3'},
    {'text': 'And ye shall know the truth, and the truth shall make you free.', 'reference': 'John 8:32'},
    {'text': 'The Lord shall fight for you, and ye shall hold your peace.', 'reference': 'Exodus 14:14'},

    // Day 301-310
    {'text': 'The righteous shall flourish like the palm tree: he shall grow like a cedar in Lebanon.', 'reference': 'Psalm 92:12'},
    {'text': 'These things I have spoken unto you, that my joy might remain in you, and that your joy might be full.', 'reference': 'John 15:11'},
    {'text': 'Lord, thou hast been our dwelling place in all generations.', 'reference': 'Psalm 90:1'},
    {'text': 'Except the Lord build the house, they labour in vain that build it.', 'reference': 'Psalm 127:1'},
    {'text': 'For I am not ashamed of the gospel of Christ: for it is the power of God unto salvation to every one that believeth.', 'reference': 'Romans 1:16'},
    {'text': 'The eyes of the Lord are upon the righteous, and his ears are open unto their cry.', 'reference': 'Psalm 34:15'},
    {'text': 'Nevertheless I am continually with thee: thou hast holden me by my right hand.', 'reference': 'Psalm 73:23'},
    {'text': 'Jesus saith unto him, Thomas, because thou hast seen me, thou hast believed: blessed are they that have not seen, and yet have believed.', 'reference': 'John 20:29'},
    {'text': 'I will lift up mine eyes unto the hills, from whence cometh my help.', 'reference': 'Psalm 121:1'},
    {'text': 'But as it is written, Eye hath not seen, nor ear heard, neither have entered into the heart of man, the things which God hath prepared for them that love him.', 'reference': '1 Corinthians 2:9'},

    // Day 311-320
    {'text': 'The Lord hath appeared of old unto me, saying, Yea, I have loved thee with an everlasting love: therefore with lovingkindness have I drawn thee.', 'reference': 'Jeremiah 31:3'},
    {'text': 'Preserve me, O God: for in thee do I put my trust.', 'reference': 'Psalm 16:1'},
    {'text': 'Whether therefore ye eat, or drink, or whatsoever ye do, do all to the glory of God.', 'reference': '1 Corinthians 10:31'},
    {'text': 'I will worship toward thy holy temple, and praise thy name for thy lovingkindness and for thy truth.', 'reference': 'Psalm 138:2'},
    {'text': 'So we may boldly say, The Lord is my helper, and I will not fear what man shall do unto me.', 'reference': 'Hebrews 13:6'},
    {'text': 'Blessed is the nation whose God is the Lord; and the people whom he hath chosen for his own inheritance.', 'reference': 'Psalm 33:12'},
    {'text': 'For he hath made him to be sin for us, who knew no sin; that we might be made the righteousness of God in him.', 'reference': '2 Corinthians 5:21'},
    {'text': 'How excellent is thy lovingkindness, O God! Therefore the children of men put their trust under the shadow of thy wings.', 'reference': 'Psalm 36:7'},
    {'text': 'Ye are the light of the world. A city that is set on an hill cannot be hid.', 'reference': 'Matthew 5:14'},
    {'text': 'For his anger endureth but a moment; in his favour is life: weeping may endure for a night, but joy cometh in the morning.', 'reference': 'Psalm 30:5'},

    // Day 321-330
    {'text': 'For ye are bought with a price: therefore glorify God in your body, and in your spirit, which are God\'s.', 'reference': '1 Corinthians 6:20'},
    {'text': 'Shew me thy ways, O Lord; teach me thy paths. Lead me in thy truth, and teach me.', 'reference': 'Psalm 25:4-5'},
    {'text': 'But whosoever drinketh of the water that I shall give him shall never thirst.', 'reference': 'John 4:14'},
    {'text': 'Thou art my hiding place; thou shalt preserve me from trouble; thou shalt compass me about with songs of deliverance.', 'reference': 'Psalm 32:7'},
    {'text': 'The Lord is good unto them that wait for him, to the soul that seeketh him.', 'reference': 'Lamentations 3:25'},
    {'text': 'I will sing of the mercies of the Lord for ever: with my mouth will I make known thy faithfulness to all generations.', 'reference': 'Psalm 89:1'},
    {'text': 'Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven.', 'reference': 'Matthew 5:16'},
    {'text': 'The Lord God is my strength, and he will make my feet like hinds\' feet, and he will make me to walk upon mine high places.', 'reference': 'Habakkuk 3:19'},
    {'text': 'O Lord, thou art my God; I will exalt thee, I will praise thy name.', 'reference': 'Isaiah 25:1'},
    {'text': 'For the eyes of the Lord run to and fro throughout the whole earth, to shew himself strong in the behalf of them whose heart is perfect toward him.', 'reference': '2 Chronicles 16:9'},

    // Day 331-340
    {'text': 'Behold, God is my salvation; I will trust, and not be afraid: for the Lord Jehovah is my strength and my song.', 'reference': 'Isaiah 12:2'},
    {'text': 'I have fought a good fight, I have finished my course, I have kept the faith.', 'reference': '2 Timothy 4:7'},
    {'text': 'My help cometh from the Lord, which made heaven and earth.', 'reference': 'Psalm 121:2'},
    {'text': 'And let the beauty of the Lord our God be upon us: and establish thou the work of our hands upon us.', 'reference': 'Psalm 90:17'},
    {'text': 'So teach us to number our days, that we may apply our hearts unto wisdom.', 'reference': 'Psalm 90:12'},
    {'text': 'I, even I, am he that blotteth out thy transgressions for mine own sake, and will not remember thy sins.', 'reference': 'Isaiah 43:25'},
    {'text': 'Sing unto the Lord, O ye saints of his, and give thanks at the remembrance of his holiness.', 'reference': 'Psalm 30:4'},
    {'text': 'For all have sinned, and come short of the glory of God; being justified freely by his grace.', 'reference': 'Romans 3:23-24'},
    {'text': 'I will be glad and rejoice in thee: I will sing praise to thy name, O thou most High.', 'reference': 'Psalm 9:2'},
    {'text': 'The Spirit itself beareth witness with our spirit, that we are the children of God.', 'reference': 'Romans 8:16'},

    // Day 341-350
    {'text': 'Thou art my God, and I will praise thee: thou art my God, I will exalt thee.', 'reference': 'Psalm 118:28'},
    {'text': 'For where envying and strife is, there is confusion and every evil work. But the wisdom that is from above is first pure, then peaceable.', 'reference': 'James 3:16-17'},
    {'text': 'The Lord upholdeth all that fall, and raiseth up all those that be bowed down.', 'reference': 'Psalm 145:14'},
    {'text': 'Watch ye, stand fast in the faith, quit you like men, be strong.', 'reference': '1 Corinthians 16:13'},
    {'text': 'Blessed be the Lord, who daily loadeth us with benefits, even the God of our salvation.', 'reference': 'Psalm 68:19'},
    {'text': 'Rejoice evermore. Pray without ceasing. In every thing give thanks: for this is the will of God in Christ Jesus concerning you.', 'reference': '1 Thessalonians 5:16-18'},
    {'text': 'I will mention the lovingkindnesses of the Lord, and the praises of the Lord, according to all that the Lord hath bestowed on us.', 'reference': 'Isaiah 63:7'},
    {'text': 'The Lord is great, and greatly to be praised in the city of our God, in the mountain of his holiness.', 'reference': 'Psalm 48:1'},
    {'text': 'For he satisfieth the longing soul, and filleth the hungry soul with goodness.', 'reference': 'Psalm 107:9'},
    {'text': 'Fear not, little flock; for it is your Father\'s good pleasure to give you the kingdom.', 'reference': 'Luke 12:32'},

    // Day 351-360
    {'text': 'The Lord hath been mindful of us: he will bless us.', 'reference': 'Psalm 115:12'},
    {'text': 'Continue in prayer, and watch in the same with thanksgiving.', 'reference': 'Colossians 4:2'},
    {'text': 'He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty. I will say of the Lord, He is my refuge.', 'reference': 'Psalm 91:1-2'},
    {'text': 'For this God is our God for ever and ever: he will be our guide even unto death.', 'reference': 'Psalm 48:14'},
    {'text': 'The Lord hath done great things for us; whereof we are glad.', 'reference': 'Psalm 126:3'},
    {'text': 'Nay, in all these things we are more than conquerors through him that loved us.', 'reference': 'Romans 8:37'},
    {'text': 'Oh how great is thy goodness, which thou hast laid up for them that fear thee.', 'reference': 'Psalm 31:19'},
    {'text': 'Grace be unto you, and peace, from God our Father, and from the Lord Jesus Christ.', 'reference': '1 Corinthians 1:3'},
    {'text': 'I will praise thee, O Lord, with my whole heart; I will shew forth all thy marvellous works.', 'reference': 'Psalm 9:1'},
    {'text': 'The Lord is thy keeper: the Lord is thy shade upon thy right hand.', 'reference': 'Psalm 121:5'},

    // Day 361-365
    {'text': 'The Lord thy God, he will go over before thee, and he will destroy these nations from before thee.', 'reference': 'Deuteronomy 31:3'},
    {'text': 'Thanks be unto God for his unspeakable gift.', 'reference': '2 Corinthians 9:15'},
    {'text': 'Great is our Lord, and of great power: his understanding is infinite.', 'reference': 'Psalm 147:5'},
    {'text': 'For the Lord is good; his mercy is everlasting; and his truth endureth to all generations.', 'reference': 'Psalm 100:5'},
    {'text': 'The grace of the Lord Jesus Christ, and the love of God, and the communion of the Holy Ghost, be with you all.', 'reference': '2 Corinthians 13:14'},
  ];

  static Map<String, String> getRandomVerse() {
    final index = DateTime.now().millisecondsSinceEpoch % verses.length;
    return verses[index];
  }

  static Map<String, String> getVerseForDate(DateTime date) {
    final dayOfYear = date.difference(DateTime(date.year, 1, 1)).inDays;
    return verses[dayOfYear % verses.length];
  }
}
